title: What's On
email: boxoffice@paradise-green.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  What's On at Paradise Green
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: paradisegreenuk 
github_username:  samozzy
timezone: Europe/Edinburgh
event_title: Fringe 2023 

fringe_time: 2023-08-01 06:00 
start_date: 2023-08-04
end_date: 2023-08-28
test_date: 2023-08-09 14:30

paradise_blue: 0B0099

test_data: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - api.sh 
  - docker-compose.yml 

strict_front_matter: true 
livereload: true 

plugins:
  - bootstrap 
  - jekyll-datapage-generator

sass:
    sass_dir: _sass
    style: expanded 
    load_paths:
      - _sass 
      - vendor/bundle/ruby/*/gems/bootstrap*/assets/stylesheets/ # GitHub Pages/Action 
      - /opt/build/cache/bundle/ruby/*/gems/bootstrap*/assets/stylesheets/ #Netlify 
      - /usr/local/bundle/gems/bootstrap*/assets/stylesheets/ # Docker 


permalink: pretty 
collections:
  content:
    output: true
    permalink: :path/
  upcoming:
    output: true 
    permalink: :path/

page_gen-dirs: true 
page_gen:
  - data: 'shows'
    template: 'show' 
    name: 'title'  
    name_expr: record['title'].gsub('.','')
    dir: '/' 
  - data: 'venues'
    template: 'upcoming/upcoming'
    name: 'name'
    dir: '/upcoming'

defaults:
  # Defaults for pages
  - scope:
      type: content
    values:
      layout: default
  - scope:
      type: upcoming 
    values: 
      layout: upcoming/upcoming
      hide_footer: true 